### ISSUE TITLE
Rails 4 Support

### ISSUE THREAD

**Issue by deanpcmad** [fourseven/pure-sass#1]
I'm currently upgrading one of my apps to Ruby 2.0 & Rails 4.0 and just get a Sprockets::FileNotFound error when including the files in application.css. I guess this would be an issue with railsties?

**Comment by johno** [comment]
I got the same error as well, but reverting to version 0.0.2 seems to remedy it.

@deanperry out of curiosity, does the error go away when you specify `gem 'pure-sass', '0.0.2'` in your gemfile?

**Comment by deanpcmad** [comment]
Yep that fixes it  :+1:

**Comment by johno** [comment]
After a little digging it looks like I was able to narrow it down a bit:

With the current version of `0.0.3`, anything _but_ `@import "pure/all";` raised an error.

For example, `@import "pure/defaults";` would cause the error `File to import not found or unreadable: pure/forms.` to be raised.

The load paths listed don't include pure-sass:

```
File to import not found or unreadable: pure/defaults.
Load paths:
  /Users/johno/localmotion/web/app/assets/images
  /Users/johno/localmotion/web/app/assets/javascripts
  /Users/johno/localmotion/web/app/assets/stylesheets
  /Users/johno/localmotion/web/vendor/assets/javascripts
  /Users/johno/localmotion/web/vendor/assets/stylesheets
  /Users/johno/.rvm/gems/ruby-2.0.0-p0/gems/jquery-rails-3.0.2/vendor/assets/javascripts
  /Users/johno/.rvm/gems/ruby-2.0.0-p0/gems/neat-1.3.0/app/assets/stylesheets
  /Users/johno/.rvm/gems/ruby-2.0.0-p0/gems/bourbon-3.1.8/app/assets/stylesheets
  /Users/johno/.rvm/gems/ruby-2.0.0-p0/gems/coffee-rails-4.0.0/lib/assets/javascripts
```

So it appears that the `::Rails::Engine` doesn't seem to be including the assets properly.  However, in my fork, if I break out the `Engine` into it's own file and explicitly require it, the assets are included properly.

If I attempt to import a file that doesn't exist, I get the following load paths:

```
File to import not found or unreadable: pure/does_not_exist.
Load paths:
  /Users/johno/localmotion/web/app/assets/images
  /Users/johno/localmotion/web/app/assets/javascripts
  /Users/johno/localmotion/web/app/assets/stylesheets
  /Users/johno/localmotion/web/vendor/assets/javascripts
  /Users/johno/localmotion/web/vendor/assets/stylesheets
  /Users/johno/.rvm/gems/ruby-2.0.0-p0/gems/jquery-rails-3.0.2/vendor/assets/javascripts
  /Users/johno/.rvm/gems/ruby-2.0.0-p0/gems/neat-1.3.0/app/assets/stylesheets
  /Users/johno/.rvm/gems/ruby-2.0.0-p0/gems/bourbon-3.1.8/app/assets/stylesheets
  /Users/johno/.rvm/gems/ruby-2.0.0-p0/gems/coffee-rails-4.0.0/lib/assets/javascripts
  /Users/johno/.rvm/gems/ruby-2.0.0-p0/bundler/gems/pure-sass-07f31ef84b70/app/assets/stylesheets
```

What this means exactly, I'm not quite sure; though it looks to be involving the explicit require of `"pure/sass/engine"`. However, I will be submitting a PR with my fix shortly.

**Comment by fourseven** [comment]
Merged in now, thanks again.
