### ISSUE TITLE
how to use pure-sass

### ISSUE THREAD

**Issue by qqqzhch** [fourseven/pure-sass#6]
i have install pure-sass with gem 
and in config.rb  add require 'pure'
in scss file  @import 'pure/grids';
# but i meet error

E:\Users\qqloving\WebstormProjects\webfans> grunt
Running "compass:dist" (compass) task
unchanged sass/auto.scss
unchanged sass/ie.scss
unchanged sass/print.scss
    error sass/screen.scss (Line 1: File to import not found or unreadable: pure
/grids.
Load paths:
  E:/Users/qqloving/WebstormProjects/webfans/sass
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.6/frameworks/blueprint/styles
heets
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.6/frameworks/compass/styleshe
ets
  Compass::SpriteImporter)
overwrite stylesheets/screen.css
    error sass/styles.scss (Line 1 of sass/screen.scss: File to import not found
 or unreadable: pure/grids.
Load paths:
  E:/Users/qqloving/WebstormProjects/webfans/sass
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.6/frameworks/blueprint/styles
heets
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.12.6/frameworks/compass/styleshe
ets
  Compass::SpriteImporter)
overwrite stylesheets/styles.css
Compilation took 0.488s

**Comment by johno** [comment]
Sorry for the belated response @qqqzhch 

Is this for a Rails app? The gem currently leverages the Rails asset pipeline, so the import won't work outside of the Rails context.
